name: devsera
description: Developers Community

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  google_fonts:
  websafe_svg:
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/logo.png
    - asset/bg.jpg
    - asset/logoanimated.gif
    - asset/bg1.jpg
    - asset/bg2.jpg
    - asset/DE.png
